---
checkmk_server_version: "{{ checkmk_version }}"
checkmk_server_edition: "{{ checkmk_edition }}"
checkmk_server_verify_setup: 'true'

checkmk_server_sites:
  - name: "{{ checkmk_site }}"
    version: "{{ checkmk_server_version }}"
    state: started
    admin_pw: "{{ checkmk_pass }}"
    update_conflict_resolution: install

checkmk_server_configure_firewall: 'false'

checkmk_server_backup_on_update: 'true'  # Not recommended to disable this option
checkmk_server_backup_dir: /tmp
checkmk_server_backup_opts: '--no-past'
checkmk_server_allow_downgrades: 'false'

checkmk_server_epel_gpg_check: 'true'
